<?php
/**
 * Defines the StringUtilTest class
 */

namespace DominionEnterprises;
use DominionEnterprises\StringUtil as S;

/**
 * Test class for \DominionEnterprises\StringUtil.
 * Generated by PHPUnit on 2012-06-15 at 14:44:17.
 */
final class StringUtilTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @test
     * @expectedException InvalidArgumentException
     * @expectedExceptionMessage StringUtil::format() takes at least 2 arguments
     * @covers \DominionEnterprises\StringUtil::format
     */
    public function format_onlyOneArgumentn()
    {
        S::format('{0} and {1}');
    }

    /**
     * @test
     * @expectedException InvalidArgumentException
     * @covers \DominionEnterprises\StringUtil::format
     */
    public function format_nonStringCastableObject()
    {
        S::format('{0} and {1}', new \StdClass(), 'Jill');
    }

    /**
     * @test
     * @covers \DominionEnterprises\StringUtil::format
     */
    public function format_stringCastableObject()
    {
        $this->assertSame('Jack and Jill', S::format('{0} and {1}', new TestObjectWithToString(), 'Jill'));
    }

    /**
     * @test
     * @covers \DominionEnterprises\StringUtil::format
     */
    public function format_keysAreRepeatable()
    {
        $this->assertSame('AAA', S::format('{0}{0}{0}', 'A'));
    }

    /**
     * @test
     * @covers \DominionEnterprises\StringUtil::format
     */
    public function format_keyOrderDoesNotMatter()
    {
        $this->assertSame('ABC', S::format('{2}{1}{0}', 'C', 'B', 'A'));
    }

    /**
     * @test
     * @expectedException InvalidArgumentException
     * @expectedExceptionMessage $format is not a string
     * @covers \DominionEnterprises\StringUtil::format
     */
    public function format_nonStringFormat()
    {
        S::format(array(), 'C', 'B', 'A');
    }

    /**
     * @test
     * @covers \DominionEnterprises\StringUtil::endsWith
     */
    public function endsWith_matches()
    {
        $nonSuffix = null;
        $this->assertTrue(S::endsWith('bah', 'h', $nonSuffix));
        $this->assertSame('ba', $nonSuffix);
    }

    /**
     * @test
     * @covers \DominionEnterprises\StringUtil::endsWith
     */
    public function endsWith_noMatches()
    {
        $nonSuffix = null;
        $this->assertFalse(S::endsWith('bah', 'z', $nonSuffix));
        $this->assertSame('bah', $nonSuffix);
    }

    /**
     * @test
     * @expectedException InvalidArgumentException
     * @expectedExceptionMessage $string is not a string
     * @covers \DominionEnterprises\StringUtil::endsWith
     */
    public function endsWith_badTypeForSubject()
    {
        S::endsWith(true, '');
    }

    /**
     * @test
     * @expectedException InvalidArgumentException
     * @expectedExceptionMessage $suffix is not a string
     * @covers \DominionEnterprises\StringUtil::endsWith
     */
    public function endsWith_badTypeForSuffix()
    {
        S::endsWith('', true);
    }

    /**
     * @test
     * @covers \DominionEnterprises\StringUtil::endsWith
     */
    public function endsWith_emptyBoth()
    {
        $nonSuffix = null;
        $this->assertTrue(S::endsWith('', '', $nonSuffix));
        $this->assertSame('', $nonSuffix);
    }

    /**
     * @test
     * @covers \DominionEnterprises\StringUtil::endsWith
     */
    public function endsWith_emptySuffix()
    {
        $nonSuffix = null;
        $this->assertTrue(S::endsWith('a', '', $nonSuffix));
        $this->assertSame('a', $nonSuffix);
    }

    /**
     * @test
     * @covers \DominionEnterprises\StringUtil::endsWith
     */
    public function endsWith_emptySubject()
    {
        $nonSuffix = null;
        $this->assertFalse(S::endsWith('', 'b', $nonSuffix));
        $this->assertSame('', $nonSuffix);
    }
}

class TestObjectWithToString
{
    public function __toString()
    {
        return 'Jack';
    }
}
